version: "3.7"

## Pour lancer le docker-compose.prod
# Lancer la commade suivante : docker-compose -f docker-compose.prod.yml up --build

services:
    flaskdocker:
        container_name: python-geo-voice
        restart: always
        build:
            context: .
            dockerfile: './drop_voice_back/DockerFile.prod'
        ports: 
            - "5000:5000"
        volumes:
            - './:/app'
        links:
            - database-geo-voice:database-geo-voice
        networks:
            - python

    database-geo-voice:
        container_name: database-geo-voice
        image: mysql:latest
        volumes:
            - dbdata:/var/lib/mysql
        restart: always
        ports:
            - "9906:3306"
        env_file:
            - ./drop_voice_back/app/.env
        networks:
            - python

    angular-docker:
        container_name: angular-geo-voice
        build:
            context: .
            dockerfile: './drop_voice_front/Dockerfile.dev'
        ports: 
            - "4200:4200"
        volumes:
            - './:/app'
            - '/app/node_modules'


    nginx:
        container_name: nginx-geo-voice
        build: ./nginx
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - flaskdocker
            - angular-docker
        networks:
            - python

networks:
    local:
    python:

volumes:
    dbdata:
        driver: local