version: "3.7"

services:
    flaskdocker:
        container_name: python-drop-voice
        build:
            context: .
            dockerfile: './DockerFile'
        ports: 
            - "5000:5000"
        volumes:
            - './:/app'
        links:
            - db:db
        networks:
            - python
        
    db:
        container_name: db
        image: mysql:latest
        volumes:
            - dbdata:/var/lib/mysql
        restart: always
        ports:
            - "9906:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: geovoice_db
        networks:
            - mysql-phpmyadmin
            - python

    # phpmyadmin
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: db
        networks:
            - mysql-phpmyadmin

networks:
    local:
    mysql-phpmyadmin:
    python:

volumes:
    dbdata:
        driver: local

