version: "3.7"

## Pour lancer le docker-compose.prod
# Lancer la commade suivante : docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

services:
  flaskdocker:
    container_name: python-geo-voice
    build:
      context: .
      dockerfile: './DockerFile.prod'
    expose:
      - "5000"
    volumes:
      - './:/app'
    links:
      - database-geo-voice:database-geo-voice
    networks:
      - python

  database-geo-voice:
    container_name: database-geo-voice
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - "9906:3306"
    env_file:
      - ./app/.env
    networks:
      - python

  nginx:
    container_name: nginx-geo-voice
    image: nginx:latest
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #     - ./certificats:/etc/nginx/certificats:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flaskdocker
    networks:
      - python

networks:
  local:
  python:

volumes:
  dbdata:
    driver: local
