FROM python:3.11.5

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN python3 -m pip install --upgrade pip virtualenv \
    && python3 -m venv .venv \
    && . .venv/bin/activate \
    && pip install --upgrade pip

RUN pip install -r requirements.txt \
    && pip cache purge

COPY . /app

ENV FLASK_APP=app
ENV FLASK_RUN_HOST=0.0.0.0

EXPOSE 5000

CMD ["flask", "run"]
