version: "3.7"

services:
    flaskdocker:
        container_name: python-geo-voice
        build:
            context: .
            dockerfile: './DockerFile.dev'
        ports: 
            - "5000:5000"
        volumes:
            - './:/app'
        links:
            - database-geo-voice:database-geo-voice
        networks:
            - python

    database-geo-voice:
        container_name: database-geo-voice
        image: mysql:latest
        volumes:
            - dbdata:/var/lib/mysql
        restart: always
        ports:
            - "9906:3306"
        env_file:
            - ./app/.env
        networks:
            - mysql-phpmyadmin
            - python

    # phpmyadmin
    phpmyadmin:
        depends_on:
            - database-geo-voice
        image: phpmyadmin
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: database-geo-voice
        networks:
            - mysql-phpmyadmin

networks:
    local:
    mysql-phpmyadmin:
    python:

volumes:
    dbdata:
        driver: local
